### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by georgefst** [georgefst/prettyprinter-lucid#3]
We should provide a simple example in the README (input and output).

Perhaps link this to https://github.com/georgefst/prettyprinter-graphviz/issues/3.

**Comment by xave** [comment]
Any example at all would be helpful. Just showing how to set this up and a simple html is fine. Doesn't have to be some big, proprietary file (as alluded to in the other post).

**Comment by georgefst** [comment]
@xave Thoughts on this: #5? I'll make a new release unless you've got any suggestions.

**Comment by xave** [comment]
lgtm
